server:
  port: 8083
  servlet:
    context-path: /prod/api/${spring.application.name}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/postify
    username: root
    password: 2002
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
